# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.99619388 0.78262886 0.80457968 ... 0.87383611 0.95304372 0.06973604]
 [0.57538359 0.58091888 0.24915052 ... 0.00520837 0.12018901 0.77907467]
 [0.66476072 0.63282521 0.12897684 ... 0.6719989  0.40747984 0.16165781]
 ...
 [0.66837341 0.25642839 0.08006797 ... 0.83438065 0.56481553 0.08219752]
 [0.1864384  0.74368428 0.71077364 ... 0.01502162 0.74836723 0.03247232]
 [0.03624916 0.4083431  0.83356695 ... 0.87288236 0.22195644 0.50002782]]
[[0.31804567 0.36220171 0.09665423 ... 0.26114565 0.26209438 0.50854393]
 [0.71827691 0.13069746 0.64522185 ... 0.65942514 0.26012437 0.03395926]
 [0.01791186 0.08026629 0.58851289 ... 0.24101894 0.22065842 0.51349237]
 ...
 [0.80548365 0.55355685 0.10275695 ... 0.50274863 0.51272446 0.35235585]
 [0.78852996 0.60143834 0.15613693 ... 0.84995593 0.86423763 0.56897433]
 [0.59616976 0.63416676 0.56109648 ... 0.08019427 0.91435762 0.75666774]]


Без использования numpy

In [ ]:
def mult(a, b):
    n=len(a)
    c=[[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
             for k in range(n):
                  c[i][j]=c[i][j]+a[i][k]*b[k][j]
    return c

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = None
    result = np.dot(a, b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 721 ms, sys: 0 ns, total: 721 ms
Wall time: 725 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 5.04 ms, sys: 406 µs, total: 5.45 ms
Wall time: 6.78 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5216272686302545e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.56212377 0.83849278 0.5935381 ] [0.71973495 0.81104272 0.37620173]


In [ ]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [ ]:
def np_scalar_product(a,b):
    s = 0
    s = np.vdot(a, b)
    return s

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 21 µs, sys: 0 ns, total: 21 µs
Wall time: 25.3 µs
CPU times: user 42 µs, sys: 0 ns, total: 42 µs
Wall time: 46.3 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** ________________________________

Методы NumPy оказываются эффективнее, потому что они реализованы на языке программирования Python, который является интерпретируемым языком и не оптимизирован для вычислительных задач. В то же время, NumPy использует библиотеки на языке C и Fortran, которые оптимизированы для работы с числовыми вычислениями и обладают более высокой производительностью
В целом задача, выполняемая в Numpy, примерно в 5-100 раз быстрее, чем стандартный список Python, что является значительным скачком с точки зрения скорости

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = 0
  res = sum([i for i in np.diag(a) if i % 2 == 0])
  return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 3, 4, 8, 1],
       [7, 3, 9, 3, 5],
       [4, 3, 9, 3, 8],
       [2, 7, 7, 3, 8],
       [7, 3, 6, 4, 3]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 71 µs, sys: 11 µs, total: 82 µs
Wall time: 93.2 µs


8

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def cumavg_rows(matrix):
    cumsum = np.cumsum(matrix, axis=1)
    rows = np.arange(1, matrix.shape[1]+1)
    return cumsum / rows

def np_sec_av(*A):
    X = np.array(A)
    return cumavg_rows(X)


In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[6.39560434e-01 3.84695861e-01 1.96760472e-01 7.26410974e-01
 2.37468919e-01 8.53852200e-01 3.07823643e-01 7.17291504e-01
 3.33847593e-01 2.34551796e-02 7.24021472e-01 3.64417663e-01
 1.19650601e-01 7.59308593e-01 5.57596019e-01 2.90545147e-01
 7.64357676e-02 6.30770716e-01 4.72240617e-01 6.37262680e-01
 4.55083233e-01 7.74849699e-02 7.16246500e-01 6.01875903e-01
 6.35526236e-01 2.73045756e-01 7.22972805e-01 5.51691890e-01
 3.37114069e-01 2.27041284e-01 3.76974974e-01 9.83909835e-01
 2.67756149e-01 4.81851796e-01 2.64518686e-01 4.33862950e-01
 1.61609733e-01 3.14238570e-01 9.77258298e-01 4.76651803e-01
 4.87445608e-01 9.95676558e-01 2.43209363e-02 3.99396448e-01
 8.07446708e-01 2.53573505e-01 6.25235954e-01 4.39634331e-01
 6.39869014e-01 8.71844096e-01 3.32826828e-01 1.42606441e-01
 1.61129718e-01 2.56050113e-01 1.60217561e-01 4.31753350e-01
 8.72027982e-01 4.20485657e-01 4.28469498e-01 3.84686307e-01
 2.91095695e-01 3.00549957e-01 4.14261692e-01 8.23616372e-01
 2.58259207e-01 5.029609

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    new_elems = np.concatenate(([True], a[1:] != a[:-1]))
    idx = np.where(new_elems)[0]
    counts = np.diff(np.concatenate((idx, [len(a)])))
    return a[new_elems], counts

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 150 µs, sys: 24 µs, total: 174 µs
Wall time: 180 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    result = None
    new_X = np.where(np.arange(len(X)) % 2 == 0, X**3, a)
    reversed_X = new_X[::-1]
    result = np.concatenate((X, reversed_X))
    return result

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 176 µs, sys: 0 ns, total: 176 µs
Wall time: 181 µs
